### ISSUE TITLE
"View on Marketplace" Button is Broken

### ISSUE THREAD

**Issue by jherdman** [mainmatter/ember-asset-size-action#10]
<img width="1116" alt="Screen Shot 2020-05-24 at 6 00 27 AM" src="https://user-images.githubusercontent.com/3300/82751247-f088df80-9d83-11ea-9df2-18669384f75a.png">

Seems like it shouldn't be broken 😁

**Comment by mansona** [comment]
I just released a new version and made sure "release to marketplace" was ticked so I guess it's fixed now 🤷 I tested it myself but let me know if it's still not working for you (in case as the owner of the repo I can see something you can't) 

I'll close this for now but if it's still broken do let me know 👍
