### ISSUE TITLE
Display total bundle sizes

### ISSUE THREAD

**Issue by timiyay** [mainmatter/ember-asset-size-action#24]
We'd like to see total bundle sizes reported from this Github Action, in addition to the size changes already reported.

This will help us manage total bundle size over time, like setting budgets with https://github.com/kaliber5/ember-cli-bundlesize.

As a stretch goal, we'd love to have an integration option for https://github.com/kaliber5/ember-cli-bundlesize, so the total bundle size display can be customised, based on configured size budgets.

I'm happy to implement this myself and contribute a PR. Firstly, I'm trying to gauge whether that PR would have any chance of being merged. We've been using a fork of this repo for 6 months, waiting for https://github.com/simplabs/ember-asset-size-action/pull/18 to be merged, but it seems this repo isn't maintained or accepting PRs in any practical sense?

**Comment by timiyay** [comment]
I'll get a PR together for this today.

**Comment by vst** [comment]
I think that this is quite useful, especially after `ember-auto-import` v2 started producing more chunks.

**Comment by rahulk94** [comment]
This looks like quite a useful feature to pick up so +1 to getting this merged

**Comment by mansona** [comment]
This has been fixed in https://github.com/mainmatter/ember-asset-size-action/pull/64 which is really just a repurposing of https://github.com/mainmatter/ember-asset-size-action/pull/41 because I wasn't able to push to the branch that the PR was created from
