### ISSUE TITLE
How do I contribute?

### ISSUE THREAD

**Issue by NullVoxPopuli** [mainmatter/ember-asset-size-action#31]
idk what's going on with npm, but no matter what, all of node_modules is changed when I run `npm install`, even on `master` branch

**Comment by mansona** [comment]
so this is a bit of an issue with github actions I'm afraid 😞  it's documented in their "how to work with github actions" but also very briefly in the auto-generated https://github.com/simplabs/ember-asset-size-action/blob/master/docs/contributors.md

essentially GitHub made the terrible decision to force you to commit all of your node_modules for people to use your action. It has been widely criticised and they said they might do something about it, but no word yet

**Comment by mansona** [comment]
This has been fixed in #43 

Now we effectively bundle the code down to a single file (including all dependencies) and we verify that this dist file has been updated on a PR's CI so it doesn't go out of sync 👍
